# Generated by Django 4.0.1 on 2022-01-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='نام شبکه اجتماغی')),
                ('link', models.URLField(unique=True, verbose_name='لینک کاربر')),
                ('icon_tag', models.CharField(max_length=300, verbose_name='تگ ایکن')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
