# Generated by Django 4.0.1 on 2022-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_media',
            name='icon_tag',
            field=models.CharField(max_length=300, verbose_name='تگ ایکون (font awesome)'),
        ),
        migrations.AlterField(
            model_name='social_media',
            name='title',
            field=models.CharField(max_length=150, verbose_name='نام شبکه اجتماعی'),
        ),
    ]
