# Generated by Django 4.0.1 on 2022-01-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=150, verbose_name='مشخصه')),
                ('value', models.CharField(max_length=150, verbose_name='مقدار')),
            ],
            options={
                'verbose_name': 'اطلاعات فرد',
                'verbose_name_plural': 'اطلاعات فردی',
            },
        ),
        migrations.AlterModelOptions(
            name='me',
            options={'verbose_name': 'مشخصات اصلی', 'verbose_name_plural': 'مشخصات اصلی'},
        ),
    ]
