# Generated by Django 4.0.1 on 2022-01-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0002_information_alter_me_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='value',
            field=models.TextField(verbose_name='مقدار'),
        ),
    ]
