# Generated by Django 4.0.1 on 2022-01-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0003_alter_information_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='me',
            name='about_me',
            field=models.TextField(blank=True, null=True, verbose_name='درباره من'),
        ),
    ]
