# Generated by Django 4.0.1 on 2022-01-16 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0004_me_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='me',
            name='about_me',
            field=models.TextField(verbose_name='درباره من'),
        ),
    ]
