# Generated by Django 4.0.1 on 2022-01-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0006_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': 'مهارت', 'verbose_name_plural': 'مهارت ها'},
        ),
        migrations.AddField(
            model_name='skills',
            name='others',
            field=models.BooleanField(default=False, verbose_name='مهارت مرتبط'),
        ),
    ]
