# Generated by Django 4.0.1 on 2022-01-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0007_alter_skills_options_skills_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='others',
            field=models.BooleanField(default=True, verbose_name='مهارت مرتبط'),
        ),
    ]
