# Generated by Django 4.0.1 on 2022-01-16 22:28

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0008_alter_skills_others'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=200, verbose_name='سمت شغلی')),
                ('corp', models.CharField(max_length=200, verbose_name='نام شرکت')),
                ('start', django_jalali.db.models.jDateField()),
                ('end', django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='پایان همکاری(اگر تا الان هست خالی بزار)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه شغلی',
                'verbose_name_plural': 'سوابق شغلی',
            },
        ),
    ]
