# Generated by Django 4.0.1 on 2022-01-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0009_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='check_now',
            field=models.BooleanField(default=False, verbose_name='تا الان'),
        ),
    ]
