# Generated by Django 4.0.1 on 2022-01-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0011_education_alter_work_end_alter_work_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='محل تحصیل'),
        ),
    ]
