# Generated by Django 4.0.1 on 2022-01-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0012_education_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='others',
            field=models.BooleanField(default=False, verbose_name='مهارت نامرتبط'),
        ),
    ]
