# Generated by Django 4.0.1 on 2022-01-16 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0013_alter_skills_others'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='skill',
            new_name='title',
        ),
    ]
