# Generated by Django 4.0.1 on 2022-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('me', '0015_me_email_me_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CV_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_file', models.FileField(upload_to='', verbose_name='فایل رزومه')),
            ],
            options={
                'verbose_name': 'فایل رزومه',
                'verbose_name_plural': 'فایل رزومه',
            },
        ),
    ]
